---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-ground
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZG9hdGJubDlv
  CLOUDINARY_KEY: NzIxNTg5Mzk4NjY5MjU2
  CLOUDINARY_SECRET: WWIweVpRTmFSbk5GQURUNGxhdkF6VlFVZ19J
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhR0Z5YzJnd01EVWlMQ0poSWpvaVkyMDBNV2hsTUhWcE1tRTVjVEpzYzJONGRtRnRlREYxTmlKOS5TMl9lX0hLMTFJeE1yd21JQ1FpR1Fn
  DB_URL: bW9uZ29kYitzcnY6Ly9oYXJzaGhnMjAwNTpoYXJzaDEyM0AzLXRpZXItZGVwbG95bWVudC5rZ3VqaC5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9My1UaWVyLURlcGxveW1lbnQ=
  SECRET: SGFyc2gK

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: kanha05/campground:replaceImageTag
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-ground
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
